version: '3.8'

services:
  # Service Discovery (Eureka)
  eureka-server:
    build: ./eureka-server
    container_name: eureka-server
    ports:
      - "8761:8761"
    networks:
      - microservices-network

  # Department Service
  department-service:
    build: ./department-service
    container_name: department-service
    depends_on:
      - eureka-server
    ports:
      - "8081:8081"
    networks:
      - microservices-network

  # Team Service
  team-service:
    build: ./team-service
    container_name: team-service
    depends_on:
      - eureka-server
    ports:
      - "8082:8082"
    networks:
      - microservices-network

  # API Gateway
  api-gateway:
    build: ./api-gateway
    container_name: api-gateway
    depends_on:
      - eureka-server
    ports:
      - "9090:9090"
    networks:
      - microservices-network

networks:
  microservices-network:
    driver: bridge 