spring:
  application:
    name: catalogue-entreprise-microservice
  
  # Configuration de la base de données MariaDB
  datasource:
    url: jdbc:mariadb://localhost:3306/microservice_db?createDatabaseIfNotExist=true
    driver-class-name: org.mariadb.jdbc.Driver
    username: root
    password: 
    hikari:
      maximum-pool-size: 10
      minimum-idle: 2
      idle-timeout: 300000
  
  # Configuration des données initiales
  sql:
    init:
      mode: always
      data-locations: classpath:schema.sql

# Configuration du serveur
server:
  port: 8080
  servlet:
    context-path: /

# Configuration des logs
logging:
  level:
    com.entreprise.catalogue: INFO
    org.springframework.web: INFO
    org.hibernate.SQL: INFO
    org.hibernate.type.descriptor.sql.BasicBinder: INFO
  file:
    name: logs/catalogue-app.log
    max-size: 10MB
    max-history: 30
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"

# Configuration CORS
cors:
  allowed-origins: http://localhost:3000,http://localhost:4200
  allowed-methods: GET,POST,PUT,DELETE,OPTIONS
  allowed-headers: "*"

# Configuration Actuator (monitoring)
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: when-authorized
  info:
    env:
      enabled: true 