spring:
  application:
    name: team-service
  datasource:
    url: jdbc:mariadb://host.docker.internal:3306/microservices_db
    driver-class-name: org.mariadb.jdbc.Driver
    username: root
    password: 
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MariaDBDialect

server:
  port: 8082

eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:8761/eureka/
  instance:
    prefer-ip-address: true
    hostname: team-service
