spring:
  application:
    name: catalogue-entreprise-microservice
  
  # Configuration de la base de données MariaDB pour la production
  datasource:
    url: jdbc:mariadb://localhost:3306/microservice_db
    driver-class-name: org.mariadb.jdbc.Driver
    username: ${DB_USERNAME:root}
    password: ${DB_PASSWORD:}
  
  # Configuration JPA/Hibernate pour la production
  jpa:
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MariaDBDialect
        format_sql: false
  
  # Désactiver H2 Console en production
  h2:
    console:
      enabled: false

# Configuration du serveur
server:
  port: ${SERVER_PORT:8080}
  servlet:
    context-path: /

# Configuration des logs pour la production
logging:
  level:
    com.entreprise.catalogue: INFO
    org.springframework.web: WARN
    org.hibernate.SQL: WARN
    org.hibernate.type.descriptor.sql.BasicBinder: WARN
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n" 